# Generated by Django 5.0.2 on 2024-03-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_profile', models.ImageField(max_length=50, upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('starting_content', models.CharField(max_length=500)),
                ('positions', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('location', models.CharField(max_length=25)),
                ('practiceArea', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('fax', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=500)),
                ('ending_content', models.CharField(max_length=500)),
            ],
        ),
    ]
