# Generated by Django 5.0.2 on 2024-03-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='amenities',
        ),
    ]
