# Generated by Django 5.0.2 on 2024-03-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_properties_area_properties_bathroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_img',
            field=models.ImageField(upload_to='properties-img'),
        ),
    ]
