# Generated by Django 5.0.2 on 2024-03-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_alter_properties_property_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('property_name', models.CharField(max_length=30)),
                ('property_location', models.CharField(max_length=30)),
                ('property_description', models.TextField(max_length=300)),
                ('property_id', models.CharField(max_length=100)),
                ('property_area', models.CharField(max_length=25)),
                ('property_home_area', models.CharField(max_length=30)),
                ('property_baths', models.CharField(max_length=30)),
                ('property_year', models.CharField(max_length=30)),
                ('property_lots_area', models.CharField(max_length=4)),
                ('property_dimentions', models.CharField(max_length=20)),
                ('property_bed', models.CharField(max_length=20)),
                ('property_price', models.CharField(max_length=15)),
                ('property_status', models.CharField(max_length=15)),
            ],
        ),
    ]
