# Generated by Django 5.0.2 on 2024-03-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_propertydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='property_type',
            field=models.CharField(default='Buy', max_length=30),
        ),
    ]
