# Generated by Django 5.0.2 on 2024-03-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_propertydetails_property_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydetails',
            old_name='property_home_area',
            new_name='property_rooms',
        ),
    ]
