# Generated by Django 5.0.2 on 2024-03-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_rename_property_home_area_propertydetails_property_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='property_id',
        ),
    ]
