# Generated by Django 5.0.2 on 2024-03-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_alter_propertydetails_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='property_price',
            field=models.CharField(default=7500000, max_length=25),
        ),
    ]
