# Generated by Django 5.0.2 on 2024-03-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_alter_propertydetails_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='property_id',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_price',
            field=models.CharField(max_length=15),
        ),
    ]
