# Generated by Django 5.0.2 on 2024-03-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_delete_properties_propertydetails_property_agent_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamdetails',
            old_name='name',
            new_name='team_name',
        ),
    ]
