# Generated by Django 5.0.2 on 2024-03-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_rename_name_teamdetails_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_type', models.CharField(default='REAL ESTATE', max_length=30)),
                ('News_Title', models.CharField(max_length=150)),
                ('News_By', models.CharField(default='ADMIN', max_length=20)),
                ('News_Date', models.DateField()),
                ('News_paragraph', models.CharField(max_length=500)),
                ('News_paragraph_2', models.CharField(max_length=500)),
                ('News_img', models.ImageField(default='news', upload_to='news-img')),
                ('News_Sub_Title', models.CharField(max_length=150)),
                ('News_paragraph_3', models.CharField(max_length=500)),
                ('News_Sub_Title_2', models.CharField(max_length=150)),
                ('News_paragraph_4', models.CharField(max_length=500)),
                ('News_paragraph_5', models.CharField(max_length=500)),
                ('Img_news', models.ImageField(default='news', upload_to='news-img')),
                ('News_paragraph_6', models.CharField(max_length=500)),
                ('News_paragraph_7', models.CharField(max_length=500)),
            ],
        ),
    ]
