# Generated by Django 5.0.2 on 2024-03-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0019_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetails',
            name='Img_news',
            field=models.ImageField(default='newsimages', upload_to='news-images'),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='News_img',
            field=models.ImageField(default='newsimages', upload_to='news-images'),
        ),
    ]
