# Generated by Django 5.0.2 on 2024-03-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0020_alter_newsdetails_img_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetails',
            name='News_paragraph',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='News_paragraph_2',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='News_paragraph_3',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='News_paragraph_4',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='News_paragraph_5',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='News_paragraph_6',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='News_paragraph_7',
            field=models.CharField(max_length=800),
        ),
    ]
