# Generated by Django 5.0.2 on 2024-03-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0022_alter_newsdetails_news_paragraph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Title', models.CharField(max_length=150)),
                ('Service_Description', models.CharField(max_length=350)),
                ('Service_img', models.ImageField(default='servicesimages', upload_to='Service-images')),
                ('Service_Descp_1', models.CharField(max_length=2500)),
                ('Service_Descp_2', models.CharField(max_length=2500)),
                ('Service_gallery', models.ImageField(default='servicesimages', upload_to='Service-images')),
                ('Service_galleries', models.ImageField(default='servicesimages', upload_to='Service-images')),
                ('Service_Descp_3', models.CharField(max_length=2500)),
                ('Service_Descp_4', models.CharField(max_length=2500)),
            ],
        ),
    ]
