# Generated by Django 5.0.2 on 2024-03-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0023_servicedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portoflio_title', models.CharField(max_length=150)),
                ('portfolio_small_description', models.CharField(max_length=350)),
                ('portfolio_image', models.ImageField(default='portfolioimages', upload_to='Portfolio-images')),
                ('portfolio_Descriptiion', models.CharField(max_length=3000)),
                ('Portfolio_card_image', models.ImageField(default='portfolioimages', upload_to='Portfolio-images')),
                ('portfolio_caption', models.CharField(max_length=180)),
                ('portfolio_author', models.CharField(max_length=100)),
                ('portofolio_founder', models.CharField(max_length=100)),
                ('Portfolio_card_two', models.ImageField(default='portfolioimages', upload_to='Portfolio-images')),
                ('portfolio_caption_two', models.CharField(max_length=180)),
                ('portfolio_author_two', models.CharField(max_length=100)),
                ('portofolio_founder_2', models.CharField(max_length=100)),
                ('portfolio_Heading_1', models.CharField(max_length=100)),
                ('portfolio_description_1', models.CharField(max_length=1500)),
                ('portfolio_Heading_2', models.CharField(max_length=100)),
                ('portfolio_Heading_3', models.CharField(max_length=100)),
                ('portfolio_description_3', models.CharField(max_length=1500)),
                ('portfolio_Heading_4', models.CharField(max_length=100)),
                ('portfolio_description_4', models.CharField(max_length=1500)),
                ('portfolio_Heading_5', models.CharField(max_length=100)),
                ('portfolio_description_5', models.CharField(max_length=1500)),
                ('portfolio_Heading_6', models.CharField(max_length=100)),
                ('portfolio_description_6', models.CharField(max_length=1500)),
                ('portfolio_Heading_7', models.CharField(max_length=100)),
                ('portfolio_description_7', models.CharField(max_length=1500)),
                ('portoflio_Gallery_1', models.ImageField(default='portfolioimages', upload_to='Portfolio-images')),
                ('portoflio_Gallery_2', models.ImageField(default='portfolioimages', upload_to='Portfolio-images')),
                ('portfolio_description_2', models.CharField(max_length=2500)),
            ],
        ),
    ]
