# Generated by Django 5.0.2 on 2024-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0024_portfoliodetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodetails',
            name='portfolio_author_img',
            field=models.ImageField(default='portfolioimages', upload_to='Portfolio-images'),
        ),
        migrations.AddField(
            model_name='portfoliodetails',
            name='portfolio_author_img_two',
            field=models.ImageField(default='portfolioimages', upload_to='Portfolio-images'),
        ),
    ]
