# Generated by Django 5.0.2 on 2024-03-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0025_portfoliodetails_portfolio_author_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodetails',
            name='portfolio_description_end',
            field=models.CharField(default='description ends here', max_length=2500),
        ),
        migrations.AlterField(
            model_name='portfoliodetails',
            name='portfolio_description_2',
            field=models.CharField(max_length=1500),
        ),
    ]
