# Generated by Django 5.0.2 on 2024-03-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0026_portfoliodetails_portfolio_description_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='porperty_bathroom',
            field=models.CharField(default='Bathroom', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_Garage',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_Microwave',
            field=models.CharField(default='Microwave', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_air_conditioner',
            field=models.CharField(default='Air-conditioner', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_amenities',
            field=models.CharField(default='Amenities', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_basement_parking',
            field=models.CharField(default='Basement Parking', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_clubhouse',
            field=models.CharField(default='clubhouse', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_dinning_area',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_firesafety',
            field=models.CharField(default='Fire safety', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_gallery',
            field=models.ImageField(default='gallery', upload_to='properties-img'),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_gallery_2',
            field=models.ImageField(default='gallery', upload_to='properties-img'),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_gallery_3',
            field=models.ImageField(default='gallery', upload_to='properties-img'),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_garden',
            field=models.CharField(default='Garden', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_gym',
            field=models.CharField(default='Gym', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_indoorgames',
            field=models.CharField(default='indoorgames', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_laundry',
            field=models.CharField(default='laundry', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_lift',
            field=models.CharField(default='Lift', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_living_room',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_outdoorgames',
            field=models.CharField(default='outdoorgames', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_parking',
            field=models.CharField(default='parking', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_security',
            field=models.CharField(default='24x7 security', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_swimmingpool',
            field=models.CharField(default='swimmingpool', max_length=15),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_wifi',
            field=models.CharField(default='Air-conditioner', max_length=15),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_area',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_baths',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_bed',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_dimentions',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_lots_area',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_price',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_rooms',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_year',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
