# Generated by Django 5.0.2 on 2024-03-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0027_propertydetails_porperty_bathroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_img', models.ImageField(default='agent', upload_to='commercial-img')),
                ('commercial_agent_img', models.ImageField(default='agent', upload_to='commercialagent')),
                ('type', models.CharField(max_length=30)),
                ('commercial_type', models.CharField(default='Buy', max_length=30)),
                ('commercial_name', models.CharField(max_length=30)),
                ('commercial_location', models.CharField(max_length=30)),
                ('commercial_description', models.TextField(max_length=300)),
                ('commercial_id', models.CharField(max_length=100)),
                ('commercial_area', models.CharField(max_length=25)),
                ('commercial_rooms', models.CharField(max_length=30)),
                ('commercial_baths', models.CharField(max_length=30)),
                ('commercial_year', models.CharField(max_length=30)),
                ('commercial_lots_area', models.CharField(max_length=4)),
                ('commercial_dimentions', models.CharField(max_length=20)),
                ('commercial_bed', models.CharField(max_length=20)),
                ('commercial_price', models.CharField(max_length=15)),
                ('commercial_status', models.CharField(max_length=15)),
                ('commercial_living_room', models.CharField(default='lv', max_length=15)),
                ('commercial_Garage', models.CharField(default='Garage', max_length=15)),
                ('commercial_dinning_area', models.CharField(default='Dinning area', max_length=15)),
                ('commercial_bathroom', models.CharField(default='Bathroom', max_length=15)),
                ('commercial_gym', models.CharField(default='gym', max_length=15)),
                ('commercial_garden', models.CharField(default='Garden', max_length=15)),
                ('commercial_parking', models.CharField(default='parking', max_length=15)),
                ('commercial_gallery', models.ImageField(default='gallery', upload_to='commercial-img')),
                ('commercial_gallery_2', models.ImageField(default='gallery', upload_to='commercial-img')),
                ('commercial_gallery_3', models.ImageField(default='gallery', upload_to='commercial-img')),
                ('commercial_amenities', models.CharField(default='Amenities', max_length=15)),
                ('commercial_air_conditioner', models.CharField(default='Air-conditioner', max_length=15)),
                ('commercial_Microwave', models.CharField(default='Microwave', max_length=15)),
                ('commercial_swimmingpool', models.CharField(default='swimmingpool', max_length=15)),
                ('commercial_wifi', models.CharField(default='Air-conditioner', max_length=15)),
                ('commercial_laundry', models.CharField(default='laundry', max_length=15)),
                ('commercial_indoorgames', models.CharField(default='indoorgames', max_length=15)),
                ('commercial_outdoorgames', models.CharField(default='outdoorgames', max_length=15)),
                ('commercial_clubhouse', models.CharField(default='clubhouse', max_length=15)),
                ('commercial_security', models.CharField(default='24x7 security', max_length=15)),
                ('commercial_firesafety', models.CharField(default='Fire safety', max_length=15)),
                ('commercial_basement_parking', models.CharField(default='Basement Parking', max_length=15)),
                ('commercial_lift', models.CharField(default='Lift', max_length=15)),
            ],
        ),
    ]
