# Generated by Django 5.0.2 on 2024-03-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0029_frequentlyaskedquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestions',
            name='faq_total_area_sq',
            field=models.CharField(default='560', max_length=20),
        ),
    ]
