# Generated by Django 5.0.2 on 2024-03-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0030_alter_frequentlyaskedquestions_faq_total_area_sq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestions',
            name='faq_apartment_sold',
            field=models.CharField(default='197K+', max_length=20),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestions',
            name='faq_constrution',
            field=models.CharField(default='200', max_length=30),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestions',
            name='faq_rooms',
            field=models.CharField(default='250', max_length=20),
        ),
    ]
