# Generated by Django 5.0.2 on 2024-03-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0032_alter_frequentlyaskedquestions_faq_apartment_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestions',
            name='faq_rooms',
            field=models.CharField(default='250', max_length=500),
        ),
    ]
