# Generated by Django 5.0.2 on 2024-03-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0033_alter_frequentlyaskedquestions_faq_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Feedback', models.CharField(default='Hello this is feedback', max_length=1500)),
                ('Client_name', models.CharField(default='Jigar Desai', max_length=60)),
                ('Client_designation', models.CharField(default='Buyer', max_length=60)),
            ],
        ),
    ]
