# Generated by Django 5.0.2 on 2024-03-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0034_clientfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='Client_image',
            field=models.ImageField(default='client-img', upload_to='client_Feeback'),
        ),
    ]
