# Generated by Django 5.0.2 on 2024-03-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0035_clientfeedback_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='Client_Feedbacks',
            field=models.CharField(default='CLIENTS FEEDBACK', max_length=60),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='Testimonial',
            field=models.CharField(default='Our Testimonial', max_length=60),
        ),
    ]
