# Generated by Django 5.0.2 on 2024-04-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0036_clientfeedback_client_feedbacks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='property_carousel_1',
            field=models.ImageField(default='agent', upload_to='properties-img'),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_carousel_2',
            field=models.ImageField(default='agent', upload_to='properties-img'),
        ),
    ]
