# Generated by Django 5.0.2 on 2024-04-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0038_propertydetails_property_carousel_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='property_carousel_6',
        ),
    ]
