# Generated by Django 5.0.2 on 2024-04-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0039_remove_propertydetails_property_carousel_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='number_of_properties',
            field=models.CharField(default='25 Properteis', max_length=150),
        ),
    ]
