# Generated by Django 5.0.2 on 2024-04-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0040_propertydetails_number_of_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='property_subarea',
            field=models.CharField(default='Gota', max_length=50),
        ),
    ]
