# Generated by Django 5.0.2 on 2024-04-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0041_propertydetails_property_subarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='property_description_2',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
