# Generated by Django 5.0.2 on 2024-04-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0043_propertydetails_property_map_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='property_basement_parking',
            field=models.CharField(default='Basement Parking', max_length=20),
        ),
    ]
