# Generated by Django 5.0.2 on 2024-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0044_alter_propertydetails_property_basement_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_description',
            field=models.TextField(max_length=3000),
        ),
    ]
