# Generated by Django 5.0.2 on 2024-04-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0045_alter_commercialdetails_commercial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='pdf_file',
            field=models.FileField(default='E-Broucher', null=True, upload_to='pdfs/'),
        ),
    ]
