# Generated by Django 5.0.2 on 2024-04-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0046_propertydetails_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_baths',
        ),
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_bed',
        ),
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_living_room',
        ),
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_rooms',
        ),
        migrations.AddField(
            model_name='commercialdetails',
            name='commercial_reception_area',
            field=models.CharField(default='20 X 16 sqrt', max_length=15),
        ),
    ]
