# Generated by Django 5.0.2 on 2024-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0047_remove_commercialdetails_commercial_baths_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_Garage',
        ),
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_bathroom',
        ),
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_garden',
        ),
        migrations.AddField(
            model_name='commercialdetails',
            name='commercial_washroom',
            field=models.CharField(default='20 X 16 sqrt', max_length=15),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_dinning_area',
            field=models.CharField(default='20 X 16 sqrt', max_length=15),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_gym',
            field=models.CharField(default='20 X 16 sqrt', max_length=15),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_parking',
            field=models.CharField(default='20 X 16 sqrt', max_length=15),
        ),
    ]
