# Generated by Django 5.0.2 on 2024-04-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0048_remove_commercialdetails_commercial_garage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_Microwave',
        ),
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_basement_parking',
        ),
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_clubhouse',
        ),
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_indoorgames',
        ),
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_laundry',
        ),
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_outdoorgames',
        ),
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_swimmingpool',
        ),
        migrations.RemoveField(
            model_name='commercialdetails',
            name='commercial_wifi',
        ),
        migrations.AddField(
            model_name='commercialdetails',
            name='commercial_Rain_Harvesting',
            field=models.CharField(default='Rain Harvesting', max_length=15),
        ),
        migrations.AddField(
            model_name='commercialdetails',
            name='commercial_earthquake_resistant',
            field=models.CharField(default='Earthquake Resistant', max_length=15),
        ),
        migrations.AddField(
            model_name='commercialdetails',
            name='commercial_maintainance_staff',
            field=models.CharField(default='Maintainance Staff', max_length=15),
        ),
        migrations.AddField(
            model_name='commercialdetails',
            name='commercial_power_backup',
            field=models.CharField(default='Power Backup', max_length=15),
        ),
        migrations.AddField(
            model_name='commercialdetails',
            name='commercial_powerbackup',
            field=models.CharField(default='Microwave', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='commercialdetails',
            name='commercial_resevedparking',
            field=models.CharField(default='Reserved Parking', max_length=15),
        ),
        migrations.AddField(
            model_name='commercialdetails',
            name='commercial_visitor_parking',
            field=models.CharField(default='Visitor Parking', max_length=15),
        ),
        migrations.AddField(
            model_name='commercialdetails',
            name='commercial_waterstorage',
            field=models.CharField(default='Water Storage', max_length=15),
        ),
    ]
