# Generated by Django 5.0.2 on 2024-04-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0049_remove_commercialdetails_commercial_microwave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialdetails',
            name='commercial_premium_brandedfitting',
            field=models.CharField(default='Premium Branded Fitting', max_length=15),
        ),
    ]
