# Generated by Django 5.0.2 on 2024-04-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0051_remove_propertydetails_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='property_videos',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
