# Generated by Django 5.0.2 on 2024-04-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0052_alter_propertydetails_property_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_Rain_Harvesting',
            field=models.CharField(default='Rain Harvesting', max_length=30),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_air_conditioner',
            field=models.CharField(default='Air-conditioner', max_length=30),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_amenities',
            field=models.CharField(default='Amenities', max_length=30),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_earthquake_resistant',
            field=models.CharField(default='Earthquake Resistant', max_length=30),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_firesafety',
            field=models.CharField(default='Fire safety', max_length=30),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_lift',
            field=models.CharField(default='Lift', max_length=30),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_maintainance_staff',
            field=models.CharField(default='Maintainance Staff', max_length=30),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_power_backup',
            field=models.CharField(default='Power Backup', max_length=30),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_powerbackup',
            field=models.CharField(default='Microwave', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_premium_brandedfitting',
            field=models.CharField(default='Premium Branded Fitting', max_length=30),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_resevedparking',
            field=models.CharField(default='Reserved Parking', max_length=30),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_security',
            field=models.CharField(default='24x7 security', max_length=30),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_visitor_parking',
            field=models.CharField(default='Visitor Parking', max_length=30),
        ),
        migrations.AlterField(
            model_name='commercialdetails',
            name='commercial_waterstorage',
            field=models.CharField(default='Water Storage', max_length=30),
        ),
    ]
