# Generated by Django 5.0.2 on 2024-04-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0053_alter_commercialdetails_commercial_rain_harvesting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='property_videos',
            field=models.URLField(default='property video', max_length=2000, null=True),
        ),
    ]
