from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('', views.index),
    path('booking', views.booking, name='Booknow_form.html'),
    path('book', views.book, name='bookcom.html'),
    path('success', views.success, name='payment_status'),
    path('successco', views.successco, name='payment_status'),
    path('Properrty/buy/', views.sort_by_buy_property, name='sort_by_buy_property'),
    path('Properrty/sell/', views.sort_by_sell_property, name='sort_by_sell_property'),
    path('Properrty/sell/Properrty/<slug:name>', views.sortedproductdetails, name='name'),
    path('Properrty/buy/Properrty/<slug:name>', views.sortedproductdetails, name='name'),
    # path('wishlist', views.wishlist, name='wishlist.html'),
    path('error', views.error, name='404.html'),
    path('area/<slug:subarea>', views.area, name='subarea'),
    path('about', views.about, name='about.html'),
    path('account', views.account, name='account.html'),
    path('addlisting', views.addlisting, name='add-listing.html'),
    path('appointment', views.appointment, name='404.html'),
    path('Newsdetails/<slug:news_name>', views.blogdetails, name='news_name'),
    path('News', views.blog, name='blog-grid.html'),
    path('comingsoon', views.comingsoon, name='coming-soon.html'),
    path('contact', views.contact, name='contact.html'),
    path('faq', views.faq, name='faq.html'),
    path('', views.index, name='index-3.html'),
    path('porfoliodetails/<slug:portfolioname>', views.porfoliodetails, name='portfolioname'),
    path('porfolio', views.porfolio, name='portfolio.html'),
    path('property/<slug:name>', views.productdetails, name='name'),
#     path('register', views.register, name='register.html'),
    path('servicedetails/<slug:service_name>', views.servicedetails, name='service_name'),
    path('service', views.service, name='service.html'),
    path('property', views.property, name='shop-grid.html'),
    path('Properrty', views.sortedproperty, name='sortedproperty.html'),
    path('commercial', views.commercial, name='commercial.html'),
    path('commercialdetails/<slug:commercial_name>', views.commercialdetail, name='commercial_name'),
    path('shoplist', views.shoplist, name='shop-list.html'),
    path('shoprightsidebar', views.shoprightsidebar, name='shop-right-sidebar.html'),
    path('shops', views.shops, name='shop.html'),
    path('team/<slug:agent_name>', views.teamdetail, name='agent_name'),
    path('team', views.team, name='team.html'),
    path('header-footer', views.headerfooter, name='header-footer.html'),
#     path('forgot-password', views.forgotpassword, name='forgot-password'),
    path('login_user',views.login_user, name='login.html'),
    path('logout_user',views.logout_user, name='logout'),
    path('register_user',views.register_user, name='register.html'),
    path('profile_user',views.profile_user, name='profile'),
    path('edit_profile_user',views.edit_profile, name='edit_profile_user'),
    path('change_password/', views.change_password, name='change_password'),
#     path('change-password',views.changepassword, name="change-password.html"),

    # [1] Submit Email Form                             //PasswordResetView.as_view()
    # [2] Email Sent Success Message                    //PasswordResetDoneView.as_view()
    # [3] Link to Password Reset form in Email          //PasswordResetConfirmView.as_view()
    # [4] Password successfullt changed message         //PasswordResetCompleteView.as_view()

    path('reset_password/', 
         auth_views.PasswordResetView.as_view(template_name="password_reset.html"), 
         name="reset_password"),
    path('reset_password_sent/', 
         auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), 
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', 
         auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), 
         name="password_reset_complete"),
]